---
# Xiaomi Dafang
# platform: generic
# name: "Køkkenet"
# username: !secret dafang_username_kokken
# password: !secret dafang_password_kokken
# verify_ssl: false
# authentication: basic
# still_image_url: !secret dafang_still_image_url_kokken
# stream_source: !secret dafang_stream_source_kokken
# scan_interval: 5
platform: ffmpeg
name: Køkkenet
input: !secret dafang_ffmpeg_input_kokken
