---
# https://shelly.cloud/
platform: mqtt
name: "Baderum light (Badev√¶relset)"
state_topic: "shellies/shelly1-B97644/relay/0"
command_topic: "shellies/shelly1-B97644/relay/0/command"
availability_topic: "shellies/shelly1-B97644/online"
payload_on: "on"
payload_off: "off"
payload_available: "true"
payload_not_available: "false"
